export const enum EventTypes {
    REPORT_GENERATED,
    NOTIFICATION,
    DONATION,
    RECEIPT_ISSUED,
    USER_UPDATED,
    INTERNAL_ERROR,
    STRIPE_CUSTOMER_CREATED,
    STRIPE_PAYMENT_METHOD_ATTACHED,
}